### ISSUE TITLE
Compatibility with Ubuntu 14.04

### ISSUE THREAD

**Issue by yaztromo99** [2ion/lxc-ps#2]
Hi. I have made sure the dependencies are installed: python3-lxc, python3-psutil. I have also got some LXCs running currently

lxc-ps fails with:
```
Traceback (most recent call last):
  File "/usr/local/bin/lxc-ps", line 6, in <module>
    import lxc
ImportError: No module named lxc

```

**Comment by 2ion** [comment]
Could it be that you used the `pip install` command from the repository README as-is?

IIRC, `pip` on even recent Ubuntus and Debians means `python2-pip` and not `python3-pip`. Could you confirm this guess by removing uninstalling lxc-ps (for example using pip), installing `python3-pip` and then installing lxc-ls again using `pip3 install lxc-ps`?

If you used the python2 `pip`, pip will install the script just fine but 'fix' the shebang header of /usr/local/bin/lxc-ps to `#!/usr/bin/python`, which is python2, for which in turn you did not install the python-lxc and python-psutil packages, only the python3 ones, which the python2 interpreter does not see, leading to the error message you mentioned.

I could add a sentence or two to the README because the pip/pip3 situation may differ between distros.

**Comment by yaztromo99** [comment]
Thanks. You are correct. I had the wrong pip installed.

```
pip uninstall lxc-ps
apt-get install python3-pip
pip3 install lxc-ps
```

Got it running great. Thanks again for your help!

**Comment by 2ion** [comment]
Glad it worked out for you. Closing because the issue has been resolved.
